#!/bin/bash -ex

# silence locale warnings
export LC_ALL=C LANGUAGE=C LANG=C

# silence configuration questions
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
debconf-set-selections /preseed.conf

# first configuration run will have some errors
dpkg --configure -a || true

# second configuration run should succeed
mount proc -t proc /proc
dpkg --configure -a
umount /proc
