#!/bin/bash -ex

# This script is executed in a chroot environment after all packages have
# been installed but are not yet configured.  The resulting filesystem
# after this script has executed is used as the mahalia SD card image.

# global settings:
HOSTNAME=mahalia
ROOT_PASSWORD=toor

#################################################
# Configure all debian packages
#################################################

# silence locale warnings
export LC_ALL=C LANGUAGE=C LANG=C

# silence configuration questions
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
debconf-set-selections /preseed.conf

# select one locale to generate during package configuration
echo "en_GB.UTF-8 UTF-8" >/etc/locale.gen

# first configuration run will have some errors
dpkg --configure -a || true

# second configuration run should succeed while /proc is mounted
mount proc -t proc /proc
dpkg --configure -a
umount /proc

#################################################
# Adjust existing configuration
#################################################

# Replace file /etc/hosts
echo "127.0.0.1	localhost $HOSTNAME" >/etc/hosts

# Set root password
ENCRYPTED_PASSWORD=$(mkpasswd -m sha-512 "$ROOT_PASSWORD")
usermod -p "${ENCRYPTED_PASSWORD}" root

# Allow ssh for root with password
sed -i -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

# Remove ssh host keys from image
rm -f /etc/ssh/ssh_host_*

# Recreate ssh host keys on first boot, expand file system
cat << EOF > /etc/rc.local
#!/bin/sh
# Recreate ssh host keys
systemctl stop ssh
ssh-keygen -f /etc/ssh/ssh_host_rsa_key -t rsa -N ""
ssh-keygen -f /etc/ssh/ssh_host_dsa_key -t dsa -N ""
update-rc.d ssh defaults
systemctl start ssh

# Expand root file system
fdisk /dev/mmcblk0 <<FDISK
d
2
n
p
2


n
w
FDISK
resize2fs /dev/mmcblk0p2

# Remove this script after first boot
rm -f /etc/rc.local
EOF
chmod a+x /etc/rc.local

#################################################
# Clear all caches
#################################################

apt-get clean
rm -r /var/lib/apt/lists
