#!/usr/bin/env bash

# set GPIO 1_17 to output (initally low)
echo "49" > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio49/direction
echo 0 > /sys/class/gpio/gpio49/value

# set GPIO 3_19 to input
echo "115" > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio115/direction

# wait for switch to be pressed
while true; do
	if [ "$(cat /sys/class/gpio/gpio115/value)" == "0" ]; then
		echo "switch is pressed!"
		echo 1 > /sys/class/gpio/gpio49/value
		sleep 1s
		echo 0 > /sys/class/gpio/gpio49/value
	fi
	sleep 0.2s 
done
