#!/usr/bin/env bash

#
# this script is run by the service as the user mha
#

SCRIPT_PATH=$(readlink -f "$0")			# save path to this script
BASE="/usr/share/mahalia-utils"			# the base folder for the project
SETUP="/etc/mahalia_setup/config"               # the location of the configuration file

# Set defaults
MAHALIA_DEFAULT_CONFIG="/etc/mahalia_generic-hearing-aid_calibration"
MAHALIA_DEFAULT_CALIB="amplified"

source $BASE/functions.sh			# include bash functions
source $SETUP                                   # include setup file

# Read configuration 
source /configuration/mahalia.config


if [ "x$MAHALIA_CONFIG_PREFIX" == "x" ] || [ "x$mahaliaconfig" == "x" ]; then
    if [ ! -d $MAHALIA_DEFAULT_CONFIG ]; then
        echo "[mahalia] Could not find default configuration"
        exit 1
    fi
    echo "[mahalia] Using default configuration: $MAHALIA_DEFAULT_CONFIG"
    MAHALIA_CUR_CONFIG=$MAHALIA_DEFAULT_CONFIG
  else
    if [ ! -d "$MAHALIA_CONFIG_PREFIX$mahaliaconfig" ]; then
        echo "[mahalia] Could not find $mahaliaconfig configuration"
        exit 1
    fi
    echo "[mahalia] Using $mahaliaconfig configuration"
    MAHALIA_CUR_CONFIG=$MAHALIA_CONFIG_PREFIX$mahaliaconfig
fi

source $MAHALIA_CUR_CONFIG/config

if [ "x$HEADSET" == "x" ]; then
    if [ ! -d "$MAHALIA_CUR_CONFIG/headsets/$MAHALIA_DEFAULT_CALIB" ]; then
        echo "[mahalia] Could not find default calibration"
        exit 1
    fi
    echo "[mahalia] Using default headset calibration: $MAHALIA_DEFAULT_CALIB"
    MAHALIA_CUR_CALIB="/etc/mahalia/headsets/$MAHALIA_DEFAULT_CALIB"
else
    if [ ! -d "$MAHALIA_CUR_CONFIG/headsets/$HEADSET" ]; then
        echo "[mahalia] Could not find $HEADSET calibration"
        exit 1
    fi
    echo "[mahalia] Using $HEADSET calibration"
    MAHALIA_CUR_CALIB="/etc/mahalia/headsets/$HEADSET"
fi



if [ "$1" == "start" ]; then
	echo "[mahalia] Starting"

	# turn LED off
	echo none > $MAHALIA_LED/trigger

	# stop programs from previous attempts
	killall -s SIGTERM mha
  if [ "x$NOJACK" != "x" ]; then
	    killall -s SIGTERM jackd
  fi
	sleep 5

  # link mahalia content according to /configuration/mahalia.config
  sudo rm /etc/mahalia
  sudo ln -s $MAHALIA_CUR_CONFIG /etc/mahalia
  sudo chown -R mha:mha /etc/mahalia
	
  #Link in headset calibration
  rm /etc/mahalia/calibration
  ln -s  $MAHALIA_CUR_CALIB /etc/mahalia/calibration

  # Set codec registers
  /etc/mahalia/calibration/RegSet.sh

  if [ "x$NOJACK" == "x" ]; then
	# start jack audio server
	export JACK_NO_AUDIO_RESERVATION=1
	jackd $JACK_FRONT_OPTS -R -P$JACK_PRIORITY -dalsa -d$JACK_SOUNDCARD -r$JACK_SAMPLERATE -p$JACK_BUFFER -n$JACK_FRAMES $JACK_OPTS &
	sleep 20
  fi

	# turn LED on
	echo default-on > $MAHALIA_LED/trigger

	# start openMHA
	#source thismha.sh
	mha --interface=$OPENMHA_INTERFACE --port=$OPENMHA_PORT $OPENMHA_OPTS

	# restart script
#	exec "$SCRIPT_PATH"

elif [ "$1" == "stop" ]; then
	echo "[mahalia] Stopping"

	# turn LED off
	echo none > $MAHALIA_LED/trigger

	# kill the services
	killall -s SIGTERM mha
  if [ "x$NOJACK" != "x" ]; then
	    killall -s SIGTERM jackd
  fi
 
  # Reset links 
  rm /etc/mahalia/calibration
  sudo rm /etc/mahalia
  sudo ln -s $MAHALIA_CUR_CONFIG /etc/mahalia
  sudo chown -R mha:mha /etc/mahalia
  ln -s  $MAHALIA_CUR_CALIB /etc/mahalia/calibration
  exit 0

elif [ "$1" == "reload" ]; then
	echo "[mahalia] Reloading"
	$BASE/mahalia stop
	$BASE/mahalia start
fi
